[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "fib"
version = "0.0.1"
requires-python = ">=3.10"

[dependency-groups]
dev = [
    "ruff>=0.11.6",
]

