[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "fib"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.6",
    "pytest>=8.3.5",
]

[dependency-groups]
dev = [
    "ruff>=0.11.6",
]

[project.scripts]
fib = "main:main"